### ISSUE TITLE
RE-606 inconsistently saving patterns

### ISSUE THREAD

**Issue by PacificState** [sunflowr/recpu#12]
I've just built an RE-606 and am finding that my patterns aren't saving when I turn the machine off and on again. Repro:

- Turn the machine on
- Wait for a few seconds for the machine to start (if it's relevant, I'm debugging an issue where it doesn't start immediately even after replacing the TIP30)
- Enter pattern write, tap out a pattern, and observe it plays correctly
- Turn off the machine
- Wait ten seconds
- Turn the machine back on

I'm observing inconsistent write behavior, in that:

- Sometimes the pattern is saved correctly but the step length is wrong
- Sometimes the step length is wrong and recent edits (if I go back into a pattern which *did* save and add notes) aren't saved either

I believe I installed the files from the 1.4.3 release - however, I saw a mention of a similar problem on the RE-303 forum which indicated it was an issue in 1.3 (http://23.235.199.139/~re303c5/forum/topic/1397-pixie-pattern-storage/). Could this be a software bug, or could it be because the unit isn't starting immediately and the rails aren't quite right?

**Comment by PacificState** [comment]
Update: fixed the PSU issue (strapped a 2.2k across the resistor next to the TIP30), so it starts immediately - but I still can’t save patterns. I’ll try 1.2…

**Comment by sunflowr** [comment]
Thanks for the report! Don't think I've experienced this myself.. but will install both 1.3.0 and 1.4.3 and do some testing!
Will let you know once I've tested

**Comment by PacificState** [comment]
Thank-you! I've been debugging the build as it appears to have leaky transistors in the switch matrix which I need to fix, but it's not saving with 1.2 or 1.43. 

One thing - I was trying to figure out how and when patterns were saved after an edit without killing flash from repeated writes; is it after exiting edit mode?

**Comment by PacificState** [comment]
Some months later - this was resolved by fitting a new flash chip, after which the patterns are now saved correctly. Maybe ESD?
