### ISSUE TITLE
Maintain source code in github, so the community can contribute

### ISSUE THREAD

**Issue by RoelofBerg** [sunflowr/recpu#7]
Hi,

I want to contribute to your programming. Esp. for isse #4 but also to other issues. Would it be possible that you add the latest version of your code to this github repo ? (Instead of linking to a .zip). Then I can clone it, contribute to your programming and send you a pull-request, that you may or may not pull.

It's not necessary that you carry everything all alone :)

Best regards,
Roelof

**Comment by sunflowr** [comment]
Hi! At some point that is the plan :)

Only reason it's not out yet is that the hardware manufacturing cost need to brake even first. This is just a small investment guarantee in case someone suddenly cloned the hardware and started selling it. I know the risk of that is happening is small, but I want the people who invested in the manufacturing to know that they'll get their money back. I can check with them how the status is.

Once that's happened my plan is to publish the souce for the follwing reasons:
- Allow others to help me in improving the development
- Allow others to develop alternative sequencers (e.g. n0nx0x and the different x0xb0x OS)
- Gurantee that the project continue being alive even if I were to stop maintaining the code

Hope this answers everything :)
