### ISSUE TITLE
1.3.0 / RE-303: power cycling in "pattern play" or "track play" mode erases patterns

### ISSUE THREAD

**Issue by koppchen** [sunflowr/recpu#8]
Looks like there's a bug in 1.3.0 on the RE-303 that erases patterns when the unit is power cycled while in "pattern play" or "track play" modes.  I've tested this with both 1.2.0 and 1.3.0, and the issue only exists in 1.3.0.

To reproduce, on the RE-303 with 1.3.0:
1. From "pattern write" mode, program a pattern into any pattern slot (tested with pattern slots 1, 2, & 3, and "pattern group" 1)
2. Switch to pattern play mode
3. Play the pattern, to confirm it's correct
4. Power cycle the unit with the volume/power knob
5. Play the pattern again. It'll play a repeating note, instead of the pattern programmed in step 1.

Another issue that might be related: If power cycled in "pattern write" mode, the first note of a pattern in slot 1 gets overwritten with a 'C'. To test, do the same as above, but use pattern slot 1 and power cycle in "pattern write" mode.

Tested with:
* RE-303 (tested on multiple units)
* 1.3.0 app (reemu.syx) with 1.3.0 bootloader (bootloader.syx) <- bug
* 1.2.0 app (reemu.syx) with 1.3.0 bootloader (bootloader.syx) <- this works fine

Let me know if you need any additional info.

Thanks!

**Comment by sunflowr** [comment]
Thanks for submitting this bug, will investigate this right away! Sorry for any issues it's caused you.

**Comment by sunflowr** [comment]
Fixed in 1.4.3

https://github.com/sunflowr/recpu/releases/tag/v1.4.3
